[package]
name = "game-programming-rust-sample"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["chapter01", "chapter02", "chapter03", "chapter04", "chapter05", "chapter06", "chapter07", "chapter08"]
